Updae TruffleHog CI config

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -7,15 +7,24 @@ on:
       - main
 
 jobs:
-  secret-scan:
-    name: Scan for leaked secrets
+  trufflehog:
     runs-on: ubuntu-latest
-
     steps:
-      - name: Checkout
+      - name: Checkout Repository
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
-      - name: TruffleHog
+      - name: TruffleHog Filesystem Scan
+        id: trufflehog
         uses: trufflesecurity/trufflehog@main
+        continue-on-error: true
+        with:
+          path: ./
+          extra_args: --debug --results=verified,unknown
+
+      - name: Fail if secrets found
+        if: steps.trufflehog.outcome == 'failure'
+        run: |
+          echo "::error::TruffleHog found secrets in this PR!"
+          exit 1
